### ISSUE TITLE
pip install fails under OS X python 3.5 (miniconda related?)

### ISSUE THREAD

**Issue by hendriks73** [CPJKU/madmom#273]
```
pip install madmom
Collecting madmom
  Using cached madmom-0.14.1.tar.gz
    Complete output from command python setup.py egg_info:
    /Users/hendrik/miniconda3/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
      "Cython.Distutils.old_build_ext does not properly handle dependencies "
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/20/sc3z_ws14mj5zdf1rf6hql7w0000gn/T/pip-build-gu_iqrc8/madmom/setup.py", line 61, in <module>
        long_description = open('README.rst').read()
      File "/Users/hendrik/miniconda3/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7682: ordinal not in range(128)
```

It seems to me that the code 

    long_description = open('README.rst').read()
    long_description += '\n' + open('CHANGES.rst').read()

assumes that the UTF-8 file `README.rst` and `CHANGES.rst` can always be read without specifying that these files are UTF-8 encoded.

Something like:

    import codecs
    [...]
    long_description = codecs.open("README.rst", "r", "utf-8").read()
    long_description += '\n' + codecs.open("CHANGES.rst", "r", "utf-8").read()

may fix this.

**Comment by superbock** [comment]
Although I cannot reproduce this (maybe it is related to miniconda), the suggested fix is absolutely valid and I'll include it in the next release -- which should be out any time soon.

Thanks for reporting!

**Comment by hendriks73** [comment]
Thanks!

I just tested and the proposed change does indeed fix the described error.
However, a little later during installation, this happens:

```
Creating /Users/hendrik/.local/lib/python3.5/site-packages/madmom.egg-link (link to .)
madmom 0.15.dev0 is already the active version in easy-install.pth
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    classifiers=classifiers)
  File "/Users/hendrik/miniconda3/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/hendrik/miniconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/hendrik/miniconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/hendrik/miniconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/develop.py", line 34, in run
  File "/Users/hendrik/miniconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/develop.py", line 133, in install_for_development
  File "/Users/hendrik/miniconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/easy_install.py", line 721, in process_distribution
  File "/Users/hendrik/miniconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/develop.py", line 168, in install_egg_scripts
  File "/Users/hendrik/miniconda3/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 872: ordinal not in range(128)
```

Apparently, there is another file encoding issue or the `setup` requires some system settings.

**Comment by superbock** [comment]
Ok, but this should not happen, since `setup.py` defines its encoding as UTF-8. After searching a bit, this seems to be a not-so-easy-to-fix problem. One workaround may be to define the encoding in your shell, e.g. ``export LANG="en_us.UTF-8"`` or the like.

**Comment by superbock** [comment]
I changed the title, since I can't reproduce it under OSX without miniconda.

**Comment by hendriks73** [comment]
> e.g. export LANG="en_us.UTF-8" or the like.

Right on.
@stefan-balke helped me figure this one out.

    export LC_ALL=en_US.UTF-8

seems to do the trick. It does not seem to be miniconda-related.

**Comment by hendriks73** [comment]
That's perhaps something to add to the installation instructions. ;-)

**Comment by superbock** [comment]
I added an entry to the [FAQ](https://github.com/CPJKU/madmom/wiki/FAQ).
