### ISSUE TITLE
CNNKeyRecognitionProcessor Error

### ISSUE THREAD

**Issue by gyno12** [CPJKU/madmom#350]
### Expected behaviour
proc = CNNKeyRecognitionProcessor()
print proc
<madmom.features.key.CNNKeyRecognitionProcessor object at 0x...>

### Actual behaviour
AttributeError: 'module' object has no attribute 'PadLayer'

### Steps needed to reproduce the behaviour
import madmom
proc = CNNKeyRecognitionProcessor()
print proc

### Information about installed software
madmom.__version__
0.16.dev0

### Error Message
Traceback (most recent call last):
  File "/home/nd/workspace/ubuntu/madmom/learnmadmon/test_key_chord_downbeat.py", line 160, in <module>
    proc = madmom.features.CNNKeyRecognitionProcessor()
  File "/media/nd/000FCB1D000052B1/workspace/ubuntu/madmom/learnmadmon/madmom/features/key.py", line 117, in __init__
    nn = NeuralNetworkEnsemble.load(nn_files)
  File "/media/nd/000FCB1D000052B1/workspace/ubuntu/madmom/learnmadmon/madmom/ml/nn/__init__.py", line 174, in load
    networks = [NeuralNetwork.load(f) for f in nn_files]
  File "/media/nd/000FCB1D000052B1/workspace/ubuntu/madmom/learnmadmon/madmom/processors.py", line 69, in load
    obj = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1126, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'PadLayer'

**Comment by superbock** [comment]
You have to recompile the cython modules if any of the corresponding files changed. Depending on the type of installation, this can be accomplished via `python setup.py build_ext --inplace` (if installed in `develop` mode) or `python setup.py install` (for normal source installs).

**Comment by gyno12** [comment]
The problem is solved.Thanks.
