### ISSUE TITLE
pip install 404 error

### ISSUE THREAD

**Issue by mxklb** [CPJKU/madmom#464]
### Expected behaviour

Just use pip install madmon shall work (if dependencies already installed).

### Actual behaviour

madmon can't be installed via pip, madmon not found, 404 error:

```
/usr/bin/env python3 -m pip install --upgrade madmon
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement madmon
ERROR: No matching distribution found for madmon
```

When searching directly on the pypi webpage, I can't find it as well: https://pypi.org/search/?q=madmon 

Is there actually something broken, or am I doing something wrong?

Sadly I can't try madmon because of this :-(

### Steps needed to reproduce the behaviour

With more verbose output

```
/usr/bin/env python3 -m pip install --upgrade madmon -vvv
Using pip 20.3.3 from /home/xam/.local/lib/python3.6/site-packages/pip (python 3.6)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-kak841l7
Created temporary directory: /tmp/pip-req-tracker-2fcddtd6
Initialized build tracking at /tmp/pip-req-tracker-2fcddtd6
Created build tracker: /tmp/pip-req-tracker-2fcddtd6
Entered build tracker: /tmp/pip-req-tracker-2fcddtd6
Created temporary directory: /tmp/pip-install-y8bzvfq3
1 location(s) to search for versions of madmon:
* https://pypi.org/simple/madmon/
Fetching project page and analyzing links: https://pypi.org/simple/madmon/
Getting page https://pypi.org/simple/madmon/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/madmon/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/madmon/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/madmon/: 404 Client Error: Not Found for url: https://pypi.org/simple/madmon/ - skipping
Given no hashes to check 0 links for project 'madmon': discarding no candidates
ERROR: Could not find a version that satisfies the requirement madmon
ERROR: No matching distribution found for madmon
Exception information:
Traceback (most recent call last):
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'madmon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('madmon')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 312, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('madmon'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/xam/.local/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for madmon
Removed build tracker: '/tmp/pip-req-tracker-2fcddtd6'
```

### Information about installed software

- python3.6
- Linux Ubuntu1804 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mxklb** [comment]
Too bad, typo, silly me madmon != madmom :)
