### ISSUE TITLE
Installing the library

### ISSUE THREAD

**Issue by eton1234** [CPJKU/madmom#510]
When I run pip install I get an error:

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-3ds5p2rf/madmom_933b447674b94bccbf616e459443eb31/setup.py", line 12, in <module>
          from Cython.Build import cythonize, build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by eton1234** [comment]
I forgot to install the package dependencies: numpy, cython, etc.
