### ISSUE TITLE
Trouble installing package

### ISSUE THREAD

**Issue by BigBabik** [CPJKU/madmom#523]
### Expected behaviour

hey
trying to install and getting the error below, even though Cython is installed
I ran pip install Cython and then pip install madmom to be sure...

### Actual behaviour

(env) C:\Users\ccc\Desktop\fff\dj>pip install Cython
Requirement already satisfied: Cython in C:\Users\ccc\desktop\fff\dj\env\lib\site-packages (0.29.35)

(env) C:\Users\ccc\Desktop\fff\dj>pip install madmom
Collecting madmom
  Using cached madmom-0.16.1.tar.gz (20.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ccc\Desktop\fff\dj\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ccc\Desktop\fff\dj\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ccc\Desktop\fff\dj\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ccc\AppData\Local\Temp\pip-build-env-gnyieux0\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ccc\AppData\Local\Temp\pip-build-env-gnyieux0\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\ccc\AppData\Local\Temp\pip-build-env-gnyieux0\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ccc\AppData\Local\Temp\pip-build-env-gnyieux0\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Steps needed to reproduce the behaviour

pip install madmom

### Information about installed software

python 3.11 installed on windows 64 bit PC
```

**Comment by bounlith-ircam-amplify** [comment]
Hello BigBabik,

This is a known issue and already discussed in this [issue #463](https://github.com/CPJKU/madmom/issues/463). The package dependency has been fixes in the master branch, but not yet released. 

The workaround is to build madmom from scratch, or to install the Python package with the GIT URL: 
```pip install git+https://github.com/CPJKU/madmom```

Regards.

**Comment by ax-le** [comment]
Additionally, if you are installing madmom via a setup.py file, you can force the download from git in "install_requires" with the following line: `'madmom @ https://github.com/CPJKU/madmom/tarball/master#egg=madmom-0.17dev'`.

**Comment by ayub-kokabi** [comment]
```
pip install wheel setuptools
pip install madmom
```
