### ISSUE TITLE
ImportError: cannot import name 'BEATS_LSTM' from 'madmom.models' (unknown location)

### ISSUE THREAD

**Issue by drscotthawley** [CPJKU/madmom#541]
### Expected behaviour

madmom Import code would not produce any error 

### Actual behaviour

```python
  File "/home/myusername/github/madmom/madmom/features/beats.py", line 79, in __init__
    from ..models import BEATS_LSTM, BEATS_BLSTM
ImportError: cannot import name 'BEATS_LSTM' from 'madmom.models' (unknown location)
```

```
>>> from madmom.models import BEATS_LSTM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BEATS_LSTM' from 'madmom.models' (unknown location)
```

### Steps needed to reproduce the behaviour

```python
from madmom.models import BEATS_LSTM

```

### Information about installed software

```
pip install git+https://github.com/CPJKU/madmom.git
```

```python
>>> madmom.__version__
'0.17.dev0'
>>> np.__version__
'1.23.5'
>>> scipy.__version__
'1.13.1'
```

**Comment by drscotthawley** [comment]
User error. Failed to follow full [installation instructions](https://github.com/CPJKU/madmom/tree/main?tab=readme-ov-file#install-from-source)

Closing.
